* flowVCUtils
utilities for the flowVC project

[[https://github.com/bkm82/bragbrag/actions][https://github.com/bkm82/flowVCUtils/actions/workflows/tests.yml/badge.svg]]
** Installation
Clone and install the repository
#+begin_src shell
  git clone https://github.com/bkm82/flowVCUtils.git
  cd flowVCUtils.git
#+end_src

Install the package (optional add a -e after install for editable mode)
#+begin_src shell
  pip install .
#+end_src

** vtu_2bin.py
This file converts a file from a vtu file format to a .bin file that can be read and utilized by the flowVC code

For more information, refer to https://shaddenlab.berkeley.edu/uploads/releasenotes.pdf

*** coordinates.bin
the yourfilename_cordinates.bin will have a file format in the following form
 n x_0 y_0 z_0 x_1 y_1 z_1 ... x_(n-1) y_(n-1) z_(n-1)

 where

 n(int):    the number of components
 x(double): the x cordianate of the point
 y(double): the y cordianate of the point
 z(double): the z cordianate of the point

*** connectivity.bin
 the yourfilename_connectivity.bin will have a file format

 e i_0^0 i_0^1 i_0^2 i_0^3 i_1^0 i_1^1 i_1^2 i_0^3 ....

 where
 e(int):       the number of elements
 i_0:(4 ints)  the 4 elements that make up an element

*** adjacency.bin
 the yourfilename_adjacency.bin will have a file format

 e e_0^0 e_0^1 e_0^2 e_0^3 e_1^0 e_1^1 e_1^2 e_0^3 ....

 where
 e(int):       the number of elements
 i_0:(4 ints)  the 4 elements that share a common face with the element

** filerename.py
rename_vtu_files is a Python command-line tool designed to rename .vtu files in a directory. The tool renames files like all_results_00001.vtu to <directory_name>_00001.vtu, where <directory_name> is the name of the directory where the files are stored. This is particularly usefull for renaming simulation results from simvascular that default to all_results to names descriptive of the simulation conditions.

*** Usage
1. Navigate to the directory containing the files to rename
2. Run the script.
   1. \--root can be specified to point to a differnt directory

   2. \--prefix can be specified to a specified name. (Default is directory name)

   3. \--currentname can be specified if the files are not named all_results_

      #+begin_src shell
        python -m flowvcutils.filerename --root . --prefix <desired_name>
      #+end_src
*** Help
For a list of available options run:
#+begin_src shell
  python -m flowvcutils.filerename -h
#+end_src
